# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    hostname: mongo-express
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /Users/lezturay/Desktop/Docker/MERN:/home/node/app
    expose:
      - "3000"
    command: "npm start"

  nodejs:
    build:
      context: ./Dockerfiles
      dockerfile: node.dockerfile
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /Users/lezturay/Desktop/Docker/MERN:/home/node/app
    # expose:
    #   - "3000"
    ports:
      - "3000:3000"
    command: "npm start"
